### ISSUE TITLE
[PE-D][Tester C] Logger displays wrong information

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T09-2/tp#173]
The version is supposed to be `1.3`, but appears as `0.2.2ea`.

The application name is also incorrect.

![image.png](https://raw.githubusercontent.com/aureliony/ped/main/files/58461447-a5ac-4179-b96f-2d0e4c0aff31.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: aureliony/ped#11

**Comment by rertyy** [comment]
To display `v1.4` instead
