### ISSUE TITLE
[PE-D][Tester A] User Guide for editOrder says at least one optional field must be specified, but feature works without.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T09-2/tp#175]
## Problem
The User Guide and the functionality of the code do not match up.
While the User Guide specifies that one or more optional fields need to be present, the feature in the code works without it.

## From the User Guide 
![image.png](https://raw.githubusercontent.com/CaptainKeqing/ped/main/files/dede29a2-a024-49a3-8954-fe338cddd960.png)

## Executing ```editOrder 1```
Command executes with no error, and no changes made.

![image.png](https://raw.githubusercontent.com/CaptainKeqing/ped/main/files/ef5b9276-4b42-4edd-a435-de234c531218.png)

## Recommended Fix

1) Perhaps it would be good to use the similar checks that EditCommand used to see if any of it's fields are edited, otherwise it rejects the command.
2) Alternatively, if you want the command to work without any optional fields specified, it is a good idea to remove this line from the UG.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: CaptainKeqing/ped#5

**Comment by Jaspertzx** [comment]
This is considered an enhancement, added in UG.
